Repository nexgeniusupc/fitster_demo, pull requests merged in 2023-06, with the labels that each got.

#6 refactor: rewrite to use Pose Detection model
  lib/main.dart
  lib/painters/object_detector_painter.dart
  lib/painters/pose_painter.dart
  lib/utils/coordinates_translator.dart
  lib/views/camera_view.dart
  lib/views/object_detector_view.dart
  lib/views/pose_detector_view.dart
  pubspec.lock
  pubspec.yaml
Labels: refactor

#5 feat: home page
  assets/logo.png
  lib/views/home_page.dart
Labels: enhancement

#3 feat: search screen
  lib/utils/item_list.dart
  lib/views/search_view.dart
Labels: enhancement

#2 feat(ui): created item display page
  assets/men1.jpg
  lib/views/item_view.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#4 feat(ui): add list view clothing
  assets/images/image_4.png
  assets/images/image_5.png
  assets/images/image_6.png
  assets/images/image_7.png
  lib/utils/clothing_item.dart
  lib/views/clothing_list_view.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#7 feat: added main app navigation
  android/build.gradle
  lib/main.dart
  lib/utils/item_list.dart
  lib/views/camera_view.dart
  lib/views/home_page.dart
  lib/views/item_view.dart
  lib/views/pose_detector_view.dart
  lib/views/search_view.dart
Labels: enhancement

#8 chore: release v0.2.0
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/drawable-v21/launch_background.xml
  android/app/src/main/res/drawable/launch_background.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/profile/AndroidManifest.xml
  assets/logo-cut.png
  lib/utils/item_list.dart
  lib/views/clothing_list_view.dart
  pubspec.lock
  pubspec.yaml
Labels: chore
